### PR TITLE
Support Python 3.8 and Python 3.9

### PR DESCRIPTION
**Pull request by pquentin**
This won't slow down the builds thanks to the GitHub Actions parallelism.

### CODE REVIEW

**Comment by victorbenichoux** [comment]
Thanks @pquentin ! I am somehow surprised that none of the typing logic fails on 3.8-9 😄

**Comment by pquentin** [comment]
@victorbenichoux Which makes me think, do you want to run lint on 3.8 and 3.9 too?

**Comment by victorbenichoux** [comment]
> @victorbenichoux Which makes me think, do you want to run lint on 3.8 and 3.9 too?

We probably should, yes.

**Comment by pquentin** [comment]
To be clear, the standard practice is to just pick a Python version to run the lint, but you may be worried that mypy returns different results on different Python verions given your advanced tricks

**Comment by victorbenichoux** [comment]
> To be clear, the standard practice is to just pick a Python version to run the lint, but you may be worried that mypy returns different results on different Python verions given your advanced tricks

Ok, then let's not do that for now. Would you recommend to run lint with the latest version possibly? I will try to run it and see, in the meantime let's just merge this PR.

**Comment by pquentin** [comment]
I went ahead and made the change.

Also, sorry for pushing to the main repo. I'll stop doing that!

**Comment by victorbenichoux** [comment]
> I went ahead and made the change.
> 
> Also, sorry for pushing to the main repo. I'll stop doing that!

I' not sure it's bad, really. I like it better to be able to pull the branch easily TBH

**Comment by pquentin** [comment]
But if the branch is in my fork, why do you care about it?

Also, this 2x more builds means 2x more risk. Case in point, one of the lints appears to be stalled

**Comment by antoinejeannot** [comment]
Great thanks @pquentin

**Pull request merged**
